### ISSUE TITLE
normalize the stations table for lyon and bordeaux

### ISSUE THREAD

**Issue by garaud** [garaud/jitenshea#14]
* get the same table name for the list of all stations (with geom)
* the name of the columns

This can avoid to have a different table name and different column for station id for instance.

This function `controller.station_city_table` should be deleted.

**Comment by delhomer** [comment]
This issue is strongly related to issue #5 .

**Comment by garaud** [comment]
I think it's two different things:

* a db normalization with two tables in `lyon` and `bordeaux` schema with the same structure
* code factorization in several luigi tasks

**Comment by delhomer** [comment]
Ok, I understand your point. 

Anyway it participates to the same move: we should normalize the lyon and bordeaux assets...

**Comment by delhomer** [comment]
Proposition of a common `stations` table structure:
- `id`: ID of the station
- `name`: name of the station
- `address`: address of the station
- `city`: city where the station is located in
- `nb_terminal`: number of bike terminal (bikes + available stands)
- `geom`: geometry (for Postgis treatment)

These features are common to our first two city examples (`e.g.` Bordeaux and Lyon), and I am not sure that other features are relevant in our use case.

**Comment by garaud** [comment]
Agreed. I just would have replaced `nb_terminal` by `stations` or `stations_num`
