### ISSUE TITLE
number of stations can be different according to the Grand Lyon data source

### ISSUE THREAD

**Issue by garaud** [garaud/jitenshea#46]
There are more stations for Lyon in `/infostation` than `/station`.

The first one just returns the geolocalized stations which come from a data Grand Lyon shapefile. The second one gives the availability stations which come from another data Grand Lyon url.

Try to understand why there is a difference. Maybe the SHP should be updated.

**Comment by delhomer** [comment]
See for example this output on the webapp :

![image](https://user-images.githubusercontent.com/15051098/62202297-55082780-b389-11e9-81aa-220d1f3a89b4.png)

**Comment by delhomer** [comment]
After re-importing the station data into a brand new database, I can see that:
- there are 21 extra-stations in Lyon;
- the station quantity in Bordeaux is constant, however the IDs does not match the same stations any more

Maybe we should design a small script to clean the database and re-import the station data. The station data URLs look stable, by the way.
