### ISSUE TITLE
Error when loading data

### ISSUE THREAD

**Issue by bparpoil** [garaud/jitenshea#57]
The *data analysis* pages are broken with an loading error  : "DataTables warning: table id=citytable - Ajax error. For more information about this error, please see http://datatables.net/tn/7"

Map and tables are empty.

A quick test of the API gets me an error 500.

**Comment by delhomer** [comment]
An example of an API failure: data.oslandia.io/bikes/api/bordeaux/station, which gives `{"message": "Internal Server Error"}`.

**Comment by garaud** [comment]
I've got a `psycopg2` exception with an issue about postgis... strange.

**Comment by garaud** [comment]
The Web application is running back! An old version of postgis was removed. A `alter extension postgis update;` worked fine.
