### ISSUE TITLE
Add some clustering results to the web app

### ISSUE THREAD

**Issue by delhomer** [garaud/jitenshea#6]
Clustering will be integrated in the Luigi pipeline soon (see #3 ). The next target regarding this work will be to integrate some clustering results into the [Web app](http://data.oslandia.io/bikes) to provide additional dataviz features.

**Comment by garaud** [comment]
Suggestions:

* [ ] add a function to the controller module which will carry out the SQL query
* [ ] add a routing function to the API (the `webapi.py` module), e.g. `/api/<city>/cluster`
* [ ] add a page or some content to an existing page: a map with all clustered stations (a color by cluster) and the 24h-profile for each cluster

A feature branch for each stuff looks me good. Pair-programming is welcome with a sharing screen/editor.

**Comment by garaud** [comment]
closes by #18
